export const LIVE2D_R2_LOCALHOST_PROBE_ROUTE_LABELS = Object.freeze([
  "health",
  "status",
  "runtime_config",
]);

export const LIVE2D_R2_COMPACT_PROBE_ROUTE_LABEL = "r2_compact_probe_summary";
export const LIVE2D_R2_COMPACT_PROBE_ROUTE_PATH = "/renderer/r2-probe-summary";

export const LIVE2D_R2_LOCALHOST_PROBE_FAILURE_LABELS = Object.freeze([
  "route_missing",
  "route_duplicate",
  "route_unknown",
  "route_extra",
  "http_not_success",
  "content_type_invalid",
  "response_too_large",
  "invalid_utf8",
  "invalid_json",
  "response_not_json_object",
  "request_timeout",
  "schema_missing",
  "schema_mismatch",
  "required_field_missing",
  "required_field_wrong_type",
  "renderer_ready_unexpected",
  "model_loaded_unexpected",
  "scene_loaded_unexpected",
  "browser_cue_delivery_ready_unexpected",
  "runtime_readiness_claimed_unexpected",
  "production_readiness_claimed_unexpected",
  "owner_confirmation_created_unexpected",
  "owner_confirmation_confirmed_unexpected",
  "actual_ingestion_allowed_unexpected",
  "trusted_loader_enabled_unexpected",
  "trusted_loader_allowlist_enabled_unexpected",
  "priority1_not_blocked",
  "checked_row_count_not_zero",
  "motion_dataset_executable_unexpected",
  "compact_summary_missing",
  "compact_summary_not_blocked",
  "cross_surface_mismatch",
  "process_not_started",
  "process_not_stopped",
  "port_not_released",
  "host_not_loopback",
]);

export const LIVE2D_R2_LOCALHOST_PROBE_ROUTE_CONTRACTS = Object.freeze([
  {
    routeLabel: "health",
    path: "/health",
    expectedSchema: "iris_live2d_renderer_health_v1",
    surfaceRole: "process_health_safe_surface",
    requiredSelectors: Object.freeze([
      Object.freeze(["ok"]),
      Object.freeze(["schema"]),
      Object.freeze(["renderer_process_alive"]),
      Object.freeze(["renderer_ready"]),
      Object.freeze(["trusted_loader_ready_candidate"]),
      Object.freeze(["live2d_safe_summary_v2"]),
      Object.freeze(["live2d_safe_summary_v2", "overallStatus"]),
      Object.freeze(["live2d_safe_summary_v2", "priority1Status"]),
      Object.freeze(["live2d_safe_summary_v2", "checkedRowCount"]),
      Object.freeze(["live2d_safe_summary_v2", "runtimeReadinessClaimed"]),
      Object.freeze(["live2d_safe_summary_v2", "productionReadinessClaimed"]),
      Object.freeze(["live2d_safe_summary_v2", "ownerConfirmationCreated"]),
      Object.freeze(["live2d_safe_summary_v2", "ownerConfirmationConfirmed"]),
      Object.freeze(["live2d_safe_summary_v2", "trustedLoaderAllowlistEnabled"]),
      Object.freeze(["live2d_safe_summary_v2", "actualIngestionAllowed"]),
      Object.freeze(["live2d_safe_summary_v2", "motionDatasetExecutable"]),
    ]),
    optionalSelectors: Object.freeze([]),
    criticalBoundarySelectors: Object.freeze({
      rendererReady: Object.freeze(["renderer_ready"]),
      trustedLoaderEnabled: Object.freeze(["trusted_loader_ready_candidate"]),
      runtimeReadinessClaimed: Object.freeze(["live2d_safe_summary_v2", "runtimeReadinessClaimed"]),
      productionReadinessClaimed: Object.freeze(["live2d_safe_summary_v2", "productionReadinessClaimed"]),
      ownerConfirmationCreated: Object.freeze(["live2d_safe_summary_v2", "ownerConfirmationCreated"]),
      ownerConfirmationConfirmed: Object.freeze(["live2d_safe_summary_v2", "ownerConfirmationConfirmed"]),
      actualIngestionAllowed: Object.freeze(["live2d_safe_summary_v2", "actualIngestionAllowed"]),
      trustedLoaderAllowlistEnabled: Object.freeze(["live2d_safe_summary_v2", "trustedLoaderAllowlistEnabled"]),
      priority1Status: Object.freeze(["live2d_safe_summary_v2", "priority1Status"]),
      checkedRowCount: Object.freeze(["live2d_safe_summary_v2", "checkedRowCount"]),
      motionDatasetExecutable: Object.freeze(["live2d_safe_summary_v2", "motionDatasetExecutable"]),
      compactSafeSummaryV2OverallStatus: Object.freeze(["live2d_safe_summary_v2", "overallStatus"]),
    }),
    compactSummarySelector: Object.freeze(["live2d_safe_summary_v2"]),
  },
  {
    routeLabel: "status",
    path: "/status",
    expectedSchema: "iris_live2d_renderer_status_v1",
    surfaceRole: "renderer_status_safe_surface",
    requiredSelectors: Object.freeze([
      Object.freeze(["ok"]),
      Object.freeze(["schema"]),
      Object.freeze(["renderer_ready"]),
      Object.freeze(["renderer_health"]),
      Object.freeze(["renderer_health", "model_loaded"]),
      Object.freeze(["renderer_health", "scene_loaded"]),
      Object.freeze(["renderer_health", "browser_cue_delivery_ready"]),
      Object.freeze(["renderer_health", "trusted_loader_ready_candidate"]),
      Object.freeze(["live2d_safe_summary_v2"]),
      Object.freeze(["live2d_safe_summary_v2", "overallStatus"]),
      Object.freeze(["live2d_safe_summary_v2", "priority1Status"]),
      Object.freeze(["live2d_safe_summary_v2", "checkedRowCount"]),
      Object.freeze(["live2d_safe_summary_v2", "runtimeReadinessClaimed"]),
      Object.freeze(["live2d_safe_summary_v2", "productionReadinessClaimed"]),
      Object.freeze(["live2d_safe_summary_v2", "ownerConfirmationCreated"]),
      Object.freeze(["live2d_safe_summary_v2", "ownerConfirmationConfirmed"]),
      Object.freeze(["live2d_safe_summary_v2", "trustedLoaderAllowlistEnabled"]),
      Object.freeze(["live2d_safe_summary_v2", "actualIngestionAllowed"]),
      Object.freeze(["live2d_safe_summary_v2", "motionDatasetExecutable"]),
    ]),
    optionalSelectors: Object.freeze([]),
    criticalBoundarySelectors: Object.freeze({
      rendererReady: Object.freeze(["renderer_ready"]),
      modelLoaded: Object.freeze(["renderer_health", "model_loaded"]),
      sceneLoaded: Object.freeze(["renderer_health", "scene_loaded"]),
      browserCueDeliveryReady: Object.freeze(["renderer_health", "browser_cue_delivery_ready"]),
      trustedLoaderEnabled: Object.freeze(["renderer_health", "trusted_loader_ready_candidate"]),
      runtimeReadinessClaimed: Object.freeze(["live2d_safe_summary_v2", "runtimeReadinessClaimed"]),
      productionReadinessClaimed: Object.freeze(["live2d_safe_summary_v2", "productionReadinessClaimed"]),
      ownerConfirmationCreated: Object.freeze(["live2d_safe_summary_v2", "ownerConfirmationCreated"]),
      ownerConfirmationConfirmed: Object.freeze(["live2d_safe_summary_v2", "ownerConfirmationConfirmed"]),
      actualIngestionAllowed: Object.freeze(["live2d_safe_summary_v2", "actualIngestionAllowed"]),
      trustedLoaderAllowlistEnabled: Object.freeze(["live2d_safe_summary_v2", "trustedLoaderAllowlistEnabled"]),
      priority1Status: Object.freeze(["live2d_safe_summary_v2", "priority1Status"]),
      checkedRowCount: Object.freeze(["live2d_safe_summary_v2", "checkedRowCount"]),
      motionDatasetExecutable: Object.freeze(["live2d_safe_summary_v2", "motionDatasetExecutable"]),
      compactSafeSummaryV2OverallStatus: Object.freeze(["live2d_safe_summary_v2", "overallStatus"]),
    }),
    compactSummarySelector: Object.freeze(["live2d_safe_summary_v2"]),
  },
  {
    routeLabel: "runtime_config",
    path: "/renderer/runtime-config",
    expectedSchema: "iris_live2d_browser_runtime_config_v1",
    surfaceRole: "browser_runtime_config_safe_surface",
    requiredSelectors: Object.freeze([
      Object.freeze(["ok"]),
      Object.freeze(["schema"]),
      Object.freeze(["live2d_safe_summary_v2"]),
      Object.freeze(["live2d_safe_summary_v2", "overallStatus"]),
      Object.freeze(["live2d_safe_summary_v2", "priority1Status"]),
      Object.freeze(["live2d_safe_summary_v2", "checkedRowCount"]),
      Object.freeze(["live2d_safe_summary_v2", "runtimeReadinessClaimed"]),
      Object.freeze(["live2d_safe_summary_v2", "productionReadinessClaimed"]),
      Object.freeze(["live2d_safe_summary_v2", "ownerConfirmationCreated"]),
      Object.freeze(["live2d_safe_summary_v2", "ownerConfirmationConfirmed"]),
      Object.freeze(["live2d_safe_summary_v2", "trustedLoaderAllowlistEnabled"]),
      Object.freeze(["live2d_safe_summary_v2", "actualIngestionAllowed"]),
      Object.freeze(["live2d_safe_summary_v2", "motionDatasetExecutable"]),
    ]),
    optionalSelectors: Object.freeze([
      Object.freeze(["loader_selection"]),
      Object.freeze(["cue_capability_required"]),
    ]),
    criticalBoundarySelectors: Object.freeze({
      runtimeReadinessClaimed: Object.freeze(["live2d_safe_summary_v2", "runtimeReadinessClaimed"]),
      productionReadinessClaimed: Object.freeze(["live2d_safe_summary_v2", "productionReadinessClaimed"]),
      ownerConfirmationCreated: Object.freeze(["live2d_safe_summary_v2", "ownerConfirmationCreated"]),
      ownerConfirmationConfirmed: Object.freeze(["live2d_safe_summary_v2", "ownerConfirmationConfirmed"]),
      actualIngestionAllowed: Object.freeze(["live2d_safe_summary_v2", "actualIngestionAllowed"]),
      trustedLoaderAllowlistEnabled: Object.freeze(["live2d_safe_summary_v2", "trustedLoaderAllowlistEnabled"]),
      priority1Status: Object.freeze(["live2d_safe_summary_v2", "priority1Status"]),
      checkedRowCount: Object.freeze(["live2d_safe_summary_v2", "checkedRowCount"]),
      motionDatasetExecutable: Object.freeze(["live2d_safe_summary_v2", "motionDatasetExecutable"]),
      compactSafeSummaryV2OverallStatus: Object.freeze(["live2d_safe_summary_v2", "overallStatus"]),
    }),
    compactSummarySelector: Object.freeze(["live2d_safe_summary_v2"]),
  },
]);

export function getLive2dR2LocalhostProbeRouteContract(routeLabel) {
  return LIVE2D_R2_LOCALHOST_PROBE_ROUTE_CONTRACTS.find((contract) => contract.routeLabel === routeLabel) || null;
}

export function getLive2dR2TransportRoutePath(routeLabel) {
  if (routeLabel === LIVE2D_R2_COMPACT_PROBE_ROUTE_LABEL) return LIVE2D_R2_COMPACT_PROBE_ROUTE_PATH;
  return getLive2dR2LocalhostProbeRouteContract(routeLabel)?.path || "";
}
